#!/bin/bash

# 🔧 GitHub Pages Settings Verification & Manual Setup Guide

echo "🔍 GitHub Pages Configuration Guide"
echo "=================================="
echo ""

echo "📋 STEP 1: Verify Repository Settings"
echo "1. Go to: https://github.com/abhirao2901/Shoppify-Health-Kart"
echo "2. Click on 'Settings' tab (top right)"
echo "3. Scroll down to 'Pages' section (left sidebar)"
echo ""

echo "📋 STEP 2: Configure GitHub Pages Source"
echo "Current recommended settings:"
echo "   Source: 'Deploy from a branch'"
echo "   Branch: 'gh-pages'"
echo "   Folder: '/ (root)'"
echo ""
echo "Alternative if gh-pages doesn't exist:"
echo "   Source: 'GitHub Actions'"
echo "   This will use the .github/workflows/ configuration"
echo ""

echo "📋 STEP 3: Manual Deployment (if automated failed)"
echo "Run these commands in order:"
echo ""
echo "# Build the project"
echo "npm run build"
echo ""
echo "# Deploy to gh-pages branch"
echo "npm run deploy"
echo ""
echo "# If deploy fails, try manual approach:"
echo "git checkout --orphan gh-pages"
echo "git rm -rf ."
echo "cp -r dist/* ."
echo "git add ."
echo "git commit -m 'Deploy to GitHub Pages'"
echo "git push origin gh-pages"
echo "git checkout main"
echo ""

echo "📋 STEP 4: Verify Deployment"
echo "After 5-10 minutes, check:"
echo "🌐 Live URL: https://abhirao2901.github.io/Shoppify-Health-Kart"
echo ""

echo "📋 STEP 5: Troubleshooting Checklist"
echo "✅ Repository is public (not private)"
echo "✅ GitHub Pages is enabled in Settings"
echo "✅ Source is set correctly (gh-pages branch or GitHub Actions)"
echo "✅ Wait 5-10 minutes for propagation"
echo "✅ Hard refresh browser (Ctrl+Shift+R)"
echo ""

echo "🚨 Common Issues:"
echo "- Blank page: Check console errors (F12 → Console)"
echo "- 404 on assets: Verify publicPath in webpack config"
echo "- Repository private: Make it public for GitHub Pages"
echo "- Wrong branch: Should be 'gh-pages' not 'main'"
echo ""

echo "📞 Support Links:"
echo "Repository: https://github.com/abhirao2901/Shoppify-Health-Kart"
echo "Settings: https://github.com/abhirao2901/Shoppify-Health-Kart/settings/pages"
echo "Actions: https://github.com/abhirao2901/Shoppify-Health-Kart/actions"
